collections:
  - "community.general"

roles:
  - version: master
    name: macunha1.github_actions_runner
    src: "https://github.com/macunha1/ansible-github-actions-runner"

  - version: master
    name: lhazlewood.xcode_clt
    src: "https://github.com/lhazlewood/ansible-role-xcode-clt"
