---
# Android SDK configuration
android_sdk_version: "11076708"
android_sdk_checksum: "sha256:7bc5c72ba0275c80a8f19684fb92793b83a6b5c94d4d179fc5988930282d7e64"
android_build_tools_version: "34.0.0"
android_platform_versions:
  - "android-34"
  - "android-35"
android_ndk_version: "25.2.9519653"

# Paths
android_sdk_path: "{{ user_home }}/Library/Android/sdk"
android_ndk_path: "{{ android_sdk_path }}/ndk/{{ android_ndk_version }}"
android_cmdline_tools_path: "{{ android_sdk_path }}/cmdline-tools"

# Java configuration
java_version: "temurin@17"

# Additional dependencies
brew_packages:
  - ccache
  - git
  - gnu-tar
  - unzip

# Gradle configuration
gradle_properties:
  org.gradle.jvmargs: "-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  org.gradle.parallel: "true"
  org.gradle.configureondemand: "true"
  org.gradle.daemon: "false"
  reactNativeArchitectures: "arm64-v8a"
