---
- hosts: ci-02 

  tasks:
    - name: Log the path
      debug:
        msg: "{{ ansible_env.PATH }}"

  roles:
    - role: macunha1.github_actions_runner
      vars:
        tmp_download_path: "/Users/justin/Downloads"

        gh_runner_version: "2.321.0"

        gh_runner_architecture: "osx-arm64"

        gh_runner_config_labels:
          - macos
          - self-hosted
        gh_runner_installation_path: "/Users/justin/actions-runner2"
        gh_runner_workspace_path: "/Users/justin/actions-runner2/_work"
        gh_runner_name: "ci-02-new"
        gh_runner_service_user: "justin"

        gh_runner_config_url: "{{lookup('ansible.builtin.env', 'GH_RUNNER_URL')}}"
        gh_runner_config_token: "{{lookup('ansible.builtin.env', 'GH_RUNNER_TOKEN_02')}}"
