---
- hosts: all 

  vars:
    gh_runner_version: "2.321.0"
    gh_runner_installation_path: "/Users/runner/actions-runner"
    gh_runner_config_url: "{{lookup('ansible.builtin.env', 'GH_RUNNER_URL')}}"

  roles:
    - role: macunha1.github_actions_runner
      vars:
        tmp_download_path: "/Users/runner/Downloads"

        gh_runner_architecture: "osx-arm64"

        gh_runner_config_labels:
          - macos
          - self-hosted
        gh_runner_installation_path: "/Users/runner/actions-runner"
        gh_runner_workspace_path: "/Users/runner/actions-runner/_work"
        gh_runner_service_user: "runner"

        # remove once we're done building this out
        gh_runner_config_name: "ci-02"

        gh_runner_config_url: "{{lookup('ansible.builtin.env', 'GH_RUNNER_URL')}}"
        gh_runner_config_token:
          # ci-01: "{{ lookup('ansible.builtin.env', 'GH_RUNNER_TOKEN_01') }}"
          ci-02: "{{ lookup('ansible.builtin.env', 'GH_RUNNER_TOKEN_02') }}"
          ci-03: "{{ lookup('ansible.builtin.env', 'GH_RUNNER_TOKEN_03') }}"

  tasks:

    - name: Autologin runner user
      ansible.builtin.shell: |
        sudo sysadminctl -autologin set -userName runner -password {{lookup('ansible.builtin.env', 'SUDO_PASSWORD')}}

    - name: Remove the .env file if it exists
      ansible.builtin.file:
        path: "/Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/.env"
        state: absent

    - name: Replace the .env file with the contents of the .zshenv file without "export " strings and skip PATH variable
      ansible.builtin.shell: |
        grep '^export ' /Users/runner/.zshenv | sed '/^export PATH=/d; s/^export //' > /Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/.env
        echo "$PATH" > /Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/.path

    - name: Restart the runner service
      ansible.builtin.command: |
        launchctl unload /Library/LaunchDaemons/com.github.runner.{{ gh_runner_config_name }}.plist
        launchctl load /Library/LaunchDaemons/com.github.runner.{{ gh_runner_config_name }}.plist

    - name: Create the restart.sh script
      ansible.builtin.copy:
        content: |
          sudo shutdown -r +7s
        dest: "/Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/restart.sh"
        mode: '0755'

    - name: Add the ACTIONS_RUNNER_HOOK_JOB_COMPLETED to the .env file if it doesn't exist
      ansible.builtin.shell: |
        grep -q '^ACTIONS_RUNNER_HOOK_JOB_COMPLETED=' /Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/.env || echo 'ACTIONS_RUNNER_HOOK_JOB_COMPLETED=/Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/restart.sh' >> /Users/runner/actions-runner/{{ gh_runner_version }}/{{ gh_runner_config_url | hash('sha256') }}/.env
