---
- hosts: all
  tasks:
    - name: Install Volta
      community.general.homebrew:
        name: volta
        state: present
        force_formula: yes

    - name: Install Node.js
      ansible.builtin.command:
        cmd: volta install node@18

    - name: Install Yarn
      ansible.builtin.command:
        cmd: volta install yarn@4

    - name: Install eas-cli
      ansible.builtin.command:
        cmd: npm install eas-cli@10.2.1
        chdir: "{{ ansible_env.HOME }}"