---
- hosts: all
  tasks:
    - name: Install Volta
      community.general.homebrew:
        name:
          - node
          - yarn
        state: present
        force_formula: yes

    - name: Install eas-cli
      ansible.builtin.command:
        cmd: npm install eas-cli@10.2.1
        chdir: "{{ ansible_env.HOME }}"